### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/NaturalPledge#1]
## Code
- [x] Terrestrial Focus
  - [x] Iridescence (Heimdall's Focus)
    - [x] Iridescent Tree/Alt Trees
    - [x] Iridescent Wood
    - [x] Iridescent Sapling
    - [x] Iridescent Dirt
    - [x] Frozen Stars
  - [x] Dendric Suffusion (Idunn's Focus)
  - [x] Battle Magic (Thor's Focus)
  - [x] Movement Magic (Njord's Focus)
- [x] Awakened Items (and Divine Fusion)  
  Divine Fusion is similar to the Botanical Brewery. It, however, requires a Priestly Emblem to catalyze it. There are two options. The first is to provide a Priestly Emblem as a nonconsumed crafting ingredient. This, however, raises the problem of crafting with an Awakened emblem, as it's impossible to get one outside the player's Bauble Slot. The player can activate Soul Fusion with a Wand of the Forest, which will use their emblem as the catalyst.
  - [x] Duelist's Dagger (Njord's Item)  
    A dagger with the Block action. If you block at most a second before an attack, but at least 2 ticks, the damage will be reflected (and knockback applied.)
  - [x] Mjolnir the Crusher (Thor's item, duh)  
    Swinging it will throw the player forward. Hitting a player will knock them back and break anything they're blocking with.
  - [x] Apple of Immortality (Idunn's Item)  
    Prevents most environmental sources of damage for 20 minutes after consumption. Damage dealt by the Divine will be extremely potent to anyone under the Immortal effect.
  - [x] Horn of Fate (Heimdall's Item)  
    Seals mob AI away for a few seconds after blowing.
- [x] Discord
  - [x] Mortalstone  
    Holding one makes all players around you faithless. If you are holding one and you are wearing an Awakened emblem, it will be removable.
- [x] Misc
  - [x] Botanist's Toolbelt
  - [x] Rod of the Prismatic Lake
- [x] Lexicon documentation
  - [x] Spells
  - [x] Iridescence
  - [x] Awakened items
## Textures
- [x] Terrestrial Focus (Swirling dark blue orb with a black lattice at the edges)
- [x] Iridescent Tree (greyscale)
- [x] Iridescent Dirt (greyscale)
- [x] booooooxfoxes (3d model)
- [x] Mjolnir
- [x] Apple of Immortality (An _actually_ golden apple)
- [x] Horn of Fate (A golden horn with runic etchings)
- [x] Cherokee headdress (for reasons) (3d model)
- [x] Traveller's Flowstone
- [x] Iridescent Planks
- [x] new creative tabs
